ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10801 -DARDUINO_AVR_ADK -DARDUINO_ARCH_AVR
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2018a/toolbox/target/SUPPOR~1/ARDUIN~1/registry/..
STACK_SIZE = 64
